version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: alx_backend_caching_property_listings-db
    environment:
      POSTGRES_USER: alx_user         # match Django user
      POSTGRES_PASSWORD: alx_pass     # match Django password
      POSTGRES_DB: property_db        # match Django database name
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: alx_backend_caching_property_listings-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    container_name: alx_backend_caching_property_listings-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DB_NAME=property_db
      - DB_USER=alx_user
      - DB_PASSWORD=alx_pass
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data:
  redis_data:

