version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: alx_db
      POSTGRES_USER: alx_user
      POSTGRES_PASSWORD: alx_password
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

